@PlsStayHealthy_HostAddress = http://localhost:5212

GET {{PlsStayHealthy_HostAddress}}/weatherforecast/
Accept: application/json

GET {{PlsStayHealthy_HostAddress}}/api/health
Accept: application/json

###
